name: iOS CI

on:
  [ push, pull_request ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive
          fetch-depth: 0

    - name: Build
      run: |
        fastlane pack

    - name: Push Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mfuns-cocoa-webapp-${{ github.sha }}
        path: build/mfuns-cocoa-webapp.ipa
